[functions]
node_bundler = "esbuild"

# Security headers for production
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://maps.googleapis.com https://*.googletagmanager.com https://www.googletagmanager.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com data:;
      img-src 'self' data: blob: https:;
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.stripe.com https://js.stripe.com https://maps.googleapis.com https://fonts.googleapis.com https://fonts.gstatic.com https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com;
      frame-src https://js.stripe.com https://hooks.stripe.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self'
    """
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), payment=(self)"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# API security headers
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Robots-Tag = "noindex"
    Cache-Control = "no-store, no-cache, must-revalidate"

[[redirects]]
from = "/api/admin/create-user"
to = "/.netlify/functions/admin-create-user"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
command = "npm run build"
publish = "dist"

# Build optimization
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"
  NPM_CONFIG_PRODUCTION = "false"
  GENERATE_SOURCEMAP = "false"
  INLINE_RUNTIME_CHUNK = "false"